### ISSUE TITLE
Endpoint to login user

### ISSUE THREAD

**Issue by Valleon6** [Valleon6/Reward-Your-Teacher-API#13]
Registered user should be able to login with their email and password

**Comment by ishu-thakur** [comment]
Hi , i would like to contribute , please assign this issue to me .

**Comment by Valleon6** [comment]
> Hi , i would like to contribute , please assign this issue to me .

Hi Ishu. Have assigned the issue to you. However, note that I'm in my learning phase, so I'm still trying to get the hang of how some things work.

**Comment by ishu-thakur** [comment]
> > Hi , i would like to contribute , please assign this issue to me .
> 
> Hi Ishu. Have assigned the issue to you. However, note that I'm in my learning phase, so I'm still trying to get the hang of how some things work.

sure valleon6 i was going through your project and we need to fixes some of the dependency issues in the pom first of all .

**Comment by Valleon96** [comment]
Alright Ishu, thanks. You can point out the dependencies that need fixing when you can.

I've been trying my hands on different things, so my codes have been messy. Cleaned most of it up with the recent merging I made to the base branch. Sorry it didn't come before you forked from the base branch. Hopefully, we don't encounter any serious merge conflict.


Also, I was going to start working on switching from the in-memory H2 database to then using a Postgres database. Letting you know in case there is an input you want to make concerning it.

**Comment by ishu-thakur** [comment]
Hi valleon i have already make it easy for you by shifting the code from H2-database to Postgres:) plus i have fix your issue to spring security configuration( you can assign that to me also ) and i added the code for login endpoint please check :)

**Comment by Valleon6** [comment]
Hey Ishu. 
Did you just makes the Database change now? That was quick.

However, i don't know or can't see where you have pushed your own version to.
Please send in a pull request in order to merge it.

Will also assign you the next issue you asked for.

**Comment by ishu-thakur** [comment]
Hi valleon i pushed them in new branch name securityAndLogin name but yes sure i will raise PR for the same so you can merge

**Comment by Valleon6** [comment]
I can't seem to see the the branch you have created.

Also, do you mind sharing your email with me (privately) so i can link you up to the project's Sprint issues on JIRA.
I'm still trying to figure out how to import and synchronize Jira sprint board issues with Github issues

**Comment by Valleon6** [comment]
Okay, finally saw that you made the changes in your own forked repository. Thanks for the explanatory comments. It's very well appreciated.

**Comment by ishu-thakur** [comment]
your welcome valleon and yes i have updated my profile so you can connect with me on linkedIn or gmail. Please check that .
